"""
Organization  : Spacemit
Author        : Pan Junzhong
Time          : 2025-4-21
Function      : bsp usb tester

Do not edit this file directly if current file is not the template file.
Generated from template file[1] via k2_host_gen.py
本文件为脚本生成，不要直接编辑本文件，除非本文件就是源文件。
[1]template file: bsptester/static_data/usb/templates/test_usb_host_udisk_usbX_XX0.py
"""

from bsptester.static_data.usb.lib.base import BspUsbTestBase
from bsptester.static_data.usb.lib.v4l2_fps import calculate_fps_ratio
import os
from titanauto import mark, TestType
from titanauto.devices.topology import ChannelType
import sys

sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))


if os.getenv("TITAN_USB_DEVKIT", False):
    from bsptester.static_data.usb.lib.debug_config import *
else:
    from bsptester.static_data.usb.lib.config import *


Bytes = 1
MB = 1024 * 1024 * Bytes
GB = 1024 * 1024 * 1024 * Bytes

# uvc_resource_path = "/tmp/"
uvc_resource_path = "/root/"

class TestScript(BspUsbTestBase):
    """
    test usb host
    """

    def setup_testcase(self):
        hint = """K2-Support-beta-Initial0-PanJunzhong20251201"""
        self.logger.info(hint)
        self.i_need_iter_cleanners()

    def before_testcase(self):
        # ssh 2 iface problem cannot be solved, we decide just use adb now...
        self.device = self.topo.get_device()
        self.pc_device = None
        self.install_packages_for_me()

    def setup_iteration(self):
        pass

    def uvc_find_node(self, port, dual=False):
        """
        port: like "USB3_020_1"
        returns: like "video20"
        """
        bus = self.get_bus_number(port)
        # if you need to debug, copy this:
        # export BUS=usb1
        # find /sys/bus/usb/devices/$BUS/ | grep -E  "video4linux/video[0-9]+/device" | sort | head -1 | grep -oE '/video[0-9]+/' | tr -d '/'
        cmd = f"export BUS={bus}; "
        head = 4 if dual else 1
        cmd += f"find /sys/bus/usb/devices/$BUS/ | grep -E  \"video4linux/video[0-9]+/device\" | sort | head -{head} | grep -oE '/video[0-9]+/' | tr -d '/'"
        cmd += "; export BUS="
        node = self._single_line_cmd(cmd, timeout=60)
        if dual:
            node = node.split()
            if len(node) != 4:
                return None
            node, node1 = node[0], node[2]
            self.udevadm_print_usb_info(f"/dev/{node}", verbose=True)
            self.udevadm_print_usb_info(f"/dev/{node1}", verbose=True)
            if "video" in node and "video" in node1:
                return node, node1
            else:
                return None
        else:
            self.udevadm_print_usb_info(f"/dev/{node}", verbose=True)
            if "video" in node:
                return node
        return None

    def calc_width_height(self, prefix, bw):
        wh_mapping = {
            2: {1: (320, 240), 2: (640, 360), 3: (640, 480)},
            3: {1: (640, 480), 2: (1280, 720), 3: (1920, 1080)},
        }
        speed = self.get_speed(prefix)
        return wh_mapping[speed][bw]

    def v4l2_ctl_get_fmt(self, node, width, height):
        """
        node: like video20
        width: like 640
        height: like 480

        returns:
            Format Video Capture:
            Width/Height      : 640/360
            Pixel Format      : 'YUYV' (YUYV 4:2:2)
            Field             : None
            Bytes per Line    : 1280
            Size Image        : 460800
            Colorspace        : sRGB
            Transfer Function : Rec. 709
            YCbCr/HSV Encoding: ITU-R 601
            Quantization      : Default (maps to Limited Range)
            Flags             :
        """
        cmd = f"export CAM_NODE=/dev/{node}; "
        cmd += f"v4l2-ctl -d $CAM_NODE --set-fmt-video=height={height},width={width},pixelformat=YUYV --get-fmt-video"
        cmd += "; export CAM_NODE="
        o = self._single_line_cmd(cmd)
        return o

    def v4l2_ctl_probe_fmt_realwh(self, node, expected_width, expected_height):
        """
        node: like video20
        expected_width: like 640
        expected_height: like 480
        returns:
            width, height
        """
        cmd = f"export CAM_NODE=/dev/{node}; "
        cmd += f"v4l2-ctl -d $CAM_NODE --set-fmt-video=height={expected_height},width={expected_width},pixelformat=YUYV --get-fmt-video | grep -E \"Width/Height\\s+:\" | awk -F': ' '{{gsub(/ /,\"\",$2); print $2}}'"
        cmd += "; export CAM_NODE="
        o = self._single_line_cmd(cmd)
        self.logger.info(
            f"Expected to set width: {expected_width}, height: {expected_height}"
        )
        width, height = o.split("/")
        self.logger.info(
            f"V4L2-ctl read back adjusted width: {width}, height: {height}"
        )
        return width, height

    def v4l2_record_yuyv(
        self,
        node,
        width,
        height,
        frames,
        target_path=f"{uvc_resource_path}usbcam.raw",
        print_everything=False,
    ):
        """
        node: like video20
        width: like 640
        height: like 480
        frames: like 10
        """
        cmd = f"export CAM_NODE=/dev/{node}; "
        cmd += f"v4l2-ctl -d $CAM_NODE --set-fmt-video=height={height},width={width},pixelformat=YUYV --stream-mmap --stream-count={frames} --stream-to={target_path}"
        cmd += "; export CAM_NODE="
        if print_everything:
            o = self._single_line_cmd(
                cmd, timeout=frames // 20, call_back=self.print_anything_passed_in
            )
        else:
            o = self._single_line_cmd(cmd, timeout=frames // 20)
        return o

    def ffmpeg_record_yuyv2mp4(
        self,
        node,
        width,
        height,
        frames=None,
        target_path=f"{uvc_resource_path}usbcam.mp4",
        use_loop=False,
        max_duration=300,  # seconds
        max_filesize=500 * 1024 * 1024,  # bytes
    ):
        """
        use_loop = False : 原有行为，录固定 frames
        use_loop = True  : 循环录制到同一个文件名（环形覆盖）
        """

        cmd = f"export CAM_NODE=/dev/{node}; "

        base = (
            f"ffmpeg -f v4l2 "
            f"-input_format yuyv422 "
            f"-video_size {width}x{height} "
            f"-framerate 30 "
            f"-i $CAM_NODE "
            f"-c:v libx264 "
            f"-preset fast "
            f"-threads 4 "
        )

        if not use_loop:
            # ===== 原有单次录制 =====
            base += f"-frames:v {frames} "
            base += f"-progress - {target_path} "

        else:
            # ===== 循环录制分支 =====
            base += (
                f"-t {max_duration} "
                f"-f segment "
                f"-segment_time {max_duration} "
                f"-segment_wrap 1 "
                f"-reset_timestamps 1 "
                f"-fs {max_filesize} "
                f"{target_path} "
            )

        cmd += base
        cmd += "-hide_banner -loglevel info "
        cmd += f'2>&1 | tee {uvc_resource_path}cam_ffmpeg.log | grep -E "frame=|fps=|speed="'
        cmd += "; export CAM_NODE="

        timeout = frames // 20
        o = self._single_line_cmd(cmd, timeout=timeout)
        o1 = self._single_line_cmd(f"cat {uvc_resource_path}cam_ffmpeg.log")
        self.assertNotIn(
            "Conversion failed!", o1, f"ffmpeg 录制24h到 {target_path} 失败!"
        )
        return o

    def ffmpeg_record_yuyv2mp4_compacted(
        self, node, width, height, frames, target_path=f"{uvc_resource_path}usbcam.mp4"
    ):
        # 缩略图参数（按需调整）
        fps = 30
        thumb_width = 360  # 缩略图宽度（比如640x360）
        thumb_height = 360  # 缩略图高度
        video_bitrate = "200k"  # 输出低码率（500kbps，可改200k/1M）
        crf = 28  # H.264质量控制（值越大码率越低，18-28为合理范围）
        # 最终cmd（核心新增 -vf scale 缩放 + -b:v/-crf 控码率）
        cmd = f"export CAM_NODE=/dev/{node}; "
        # 采集阶段：严格保留原始分辨率/帧率/格式
        cmd += f"ffmpeg -f v4l2 -input_format yuyv422 -video_size {width}x{height} -framerate {fps} -i $CAM_NODE  "
        # 编码阶段：缩放为缩略图 + 低码率 + 保持帧率
        cmd += f"-vf scale={thumb_width}:{thumb_height} "  # 缩放为缩略图（核心）
        cmd += f"-c:v libx264 -threads 4 -preset fast -b:v {video_bitrate} -crf {crf} "  # 低码率控制
        cmd += f"-r {fps} -frames:v {frames} -progress - {target_path} -hide_banner -y -loglevel info  "  # 强制输出帧率和原始一致
        cmd += f'2>&1 | tee {uvc_resource_path}cam_ffmpeg.log | grep -E "frame=|fps=|speed="'
        cmd += "; export CAM_NODE="
        o = self._single_line_cmd(cmd, timeout=frames // 20)
        return o

    def ffmpeg_yuyv2mp4(self, width, height, raw_path, mp4_path):
        cmd = f"ffmpeg -f rawvideo -pix_fmt yuyv422 -s {width}x{height} -r 30 -i {raw_path} -c:v libx264 -threads 4 -preset fast -crf 23 {mp4_path} -y"
        self._single_line_cmd(cmd, timeout=360)
        o = self._single_line_cmd(f"file {mp4_path}")
        self.assertIn("Media", o, f"ffmpeg 转换 {raw_path} 到 {mp4_path} 失败!")

    def v4l2_check_record_framerate(self, log_framerate, target_fps=30):
        ratio, valid_cnt, total_cnt = calculate_fps_ratio(
            self, log_framerate, target_fps, cold_boot_lines=10
        )
        self.assertGreater(
            ratio,
            0.9,
            f"fps match target {target_fps} ratio {ratio} is too low, valid_cnt: {valid_cnt}, total_cnt: {total_cnt}",
        )

    def video_v4l2_test(
        self,
        prefix,
        bw,
        record_time,
        check_fps=False,
        verbose=False,
        should_na=True,
        no_output=False,
    ):
        framerate = 30
        node = self.uvc_find_node(prefix)
        if node is None:
            self.fail(
                f"找不到uvc webacm，检查是否插入要USB{self.get_speed(prefix)}.0规格的uvc webcam到{self.board_model.value}的{prefix}接口？!"
            )
        raw_path = f"{uvc_resource_path}usb{prefix}{node}_bw{bw}_{record_time}s.raw"
        mp4_path = f"{uvc_resource_path}usb{prefix}{node}_bw{bw}_{record_time}s.mp4"
        if no_output:
            self.logger.info(
                "考虑到长时间录制raw文件太大，此测试只拉取数据丢弃，不输出到文件，直接到 /dev/null"
            )
            raw_path = "/dev/null"
            mp4_path = "/dev/null"
        width, height = self.calc_width_height(prefix, bw)
        self.logger.info(f"Expected to set width: {width}, height: {height}")
        width, height = self.v4l2_ctl_probe_fmt_realwh(node, width, height)
        self.logger.info(
            f"V4L2-ctl read back adjusted width: {width}, height: {height}"
        )
        o = self.v4l2_record_yuyv(
            node,
            width,
            height,
            record_time * framerate,
            raw_path,
            print_everything=verbose,
        )
        if check_fps:
            self.v4l2_check_record_framerate(o, framerate)

        if not no_output:
            self.ffmpeg_yuyv2mp4(width, height, raw_path, mp4_path)
            # prevent encoding cause cannot read
            hint1 = f"USB Host 摄像头录制测试通过，但是输出文件 {mp4_path} 需要人类验证（复制链接，打开播放器，ctrl+v快捷键即开始播放）"
            self.logger.info(hint1)
            hint = f"USB Host Wecam Test Half Passed, but output MP4 file {mp4_path} need Human Check"
            self.logger.info(hint)
            # only success we clean raw file, or keep as crime scene
            self._execute(f"rm -f {uvc_resource_path}usb*_bw*_*.raw")
            if should_na:
                self.assertNa(hint + hint1)
        else:
            # only success we clean raw file, or keep as crime scene
            self._execute(f"rm -f {uvc_resource_path}usb*_bw*_*.raw")

    def video_long_test(self, prefix, bw, record_time, max_file_size=GB):
        framerate = 30
        max_file_size = 1 * GB
        self.logger.info(
            f"Specificed Params: runtime={record_time}s, bw={bw}, framerate={framerate}"
        )
        node = self.uvc_find_node(prefix)
        if node is None:
            self.fail(
                f"找不到uvc webacm，检查是否插入要USB{self.get_speed(prefix)}.0规格的uvc webcam到{self.board_model.value}的{prefix}接口？!"
            )
        mp4_path_tmp = f"{uvc_resource_path}usb{prefix}{node}_bw{bw}_{record_time}s_longrun%d.mp4"
        mp4_path = f"{uvc_resource_path}usb{prefix}{node}_bw{bw}_{record_time}s_longrun0.mp4"
        width, height = self.calc_width_height(prefix, bw)
        self.logger.info(f"Expected to set width: {width}, height: {height}")
        width, height = self.v4l2_ctl_probe_fmt_realwh(node, width, height)
        self.logger.info(
            f"V4L2-ctl read back adjusted width: {width}, height: {height}"
        )
        self.ffmpeg_record_yuyv2mp4(
            node,
            width,
            height,
            record_time * framerate,
            mp4_path_tmp,
            use_loop=True,
            max_duration=record_time,
            max_filesize=max_file_size,
        )
        o = self._single_line_cmd(f"file {mp4_path}")
        self.assertIn("Media", o, f"ffmpeg 录制24h到 {mp4_path} 失败!")
        hint1 = f"USB Host 摄像头录制测试通过，但是输出文件 {mp4_path} 需要人类验证（复制链接，打开播放器，ctrl+v快捷键即开始播放）"
        self.logger.info(hint1)
        hint = f"USB Host Wecam Test Half Passed, but output MP4 file {mp4_path} need Human Check"
        self.logger.info(hint)
        # only success we clean raw file, or keep as crime scene
        self._execute(f"rm -f {uvc_resource_path}usb*_bw*_*.raw")
        self.assertNa(hint + hint1)

    ### RANGE TEMPLATE USB RANGE BEGIN####
    @mark.id("BSP_USBX_XX0_300")
    @mark.desc("(USBX_XX0)的UVC Webcam识别")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_uvc_recognize_USBX_XX0_300(self):
        prefix = "USBX_XX0"
        self.logger.info("BSP_USBX_XX0_300: (USBX_XX0)的UVC Webcam识别")
        node = self.uvc_find_node(prefix)
        width, height = self.calc_width_height(prefix, 1)
        _ = self.v4l2_ctl_get_fmt(node, width, height)
        if node is None:
            self.fail(
                "找不到uvc webacm，检查是否插入要测试的规格的uvc webcam到指定接口？!"
            )
        self.assertTrue(True, "usb host webcam test passed")

    @mark.id("BSP_USBX_XX0_301")
    @mark.desc("(USBX_XX0)的UVC Webcam低带宽出图")
    @mark.args("runtime: seconds")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_uvc_recognize_USBX_XX0_301(self, runtime=60):
        self.logger.info("BSP_USBX_XX0_301: (USBX_XX0)的UVC Webcam低带宽出图")
        self.video_v4l2_test(
            "USBX_XX0",
            bw=1,
            record_time=runtime,
            check_fps=False,
            should_na=True,
            verbose=True,
        )
        self.assertTrue(True, "usb host webcam test passed")

    @mark.id("BSP_USBX_XX0_302")
    @mark.desc("(USBX_XX0)的UVC Webcam中带宽出图")
    @mark.args("runtime: seconds")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_uvc_recognize_USBX_XX0_302(self, runtime=60):
        self.logger.info("BSP_USBX_XX0_302: (USBX_XX0)的UVC Webcam中带宽出图")
        self.video_v4l2_test(
            "USBX_XX0",
            bw=2,
            record_time=runtime,
            check_fps=False,
            should_na=True,
            verbose=True,
        )
        self.assertTrue(True, "usb host webcam test passed")

    @mark.id("BSP_USBX_XX0_303")
    @mark.desc("(USBX_XX0)的UVC Webcam高带宽出图")
    @mark.args("runtime: seconds")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_uvc_recognize_USBX_XX0_303(self, runtime=60):
        self.logger.info("BSP_USBX_XX0_303: (USBX_XX0)的UVC Webcam高带宽出图")
        self.video_v4l2_test(
            "USBX_XX0",
            bw=3,
            record_time=runtime,
            check_fps=False,
            should_na=True,
            verbose=True,
        )
        self.assertTrue(True, "usb host webcam test passed")

    @mark.id("BSP_USBX_XX0_304")
    @mark.desc("(USBX_XX0)的UVC Webcam低带宽10分钟帧率测试")
    @mark.args("runtime: seconds")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_uvc_recognize_USBX_XX0_304(self, runtime=600):
        self.logger.info("BSP_USBX_XX0_304: (USBX_XX0)的UVC Webcam高带宽10分钟帧率测试")
        self.video_v4l2_test(
            "USBX_XX0",
            bw=3,
            record_time=runtime,
            check_fps=True,
            should_na=True,
            verbose=True,
            no_output=True,
        )
        self.assertTrue(True, "usb host webcam test passed")

    @mark.id("BSP_USBX_XX0_305")
    @mark.desc("(USBX_XX0)的UVC Webcam中带宽10分钟帧率测试")
    @mark.args("runtime: seconds")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_uvc_recognize_USBX_XX0_305(self, runtime=600):
        self.logger.info("BSP_USBX_XX0_305: (USBX_XX0)的UVC Webcam中带宽10分钟帧率测试")
        self.video_v4l2_test(
            "USBX_XX0",
            bw=2,
            record_time=runtime,
            check_fps=True,
            should_na=True,
            verbose=True,
            no_output=True,
        )
        self.assertTrue(True, "usb host webcam test passed")

    @mark.id("BSP_USBX_XX0_306")
    @mark.desc("(USBX_XX0)的UVC Webcam高带宽10分钟帧率测试")
    @mark.args("runtime: seconds")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_uvc_recognize_USBX_XX0_306(self, runtime=600):
        self.logger.info("BSP_USBX_XX0_306: (USBX_XX0)的UVC Webcam高带宽10分钟帧率测试")
        self.video_v4l2_test(
            "USBX_XX0",
            bw=3,
            record_time=runtime,
            check_fps=True,
            should_na=True,
            verbose=True,
            no_output=True,
        )
        self.assertTrue(True, "usb host webcam test passed")

    @mark.id("BSP_USBX_XX0_307")
    @mark.desc("(USBX_XX0)的UVC Webcam低带宽24h帧率测试")
    @mark.args("runtime:default 24h in sec(1-86400 allowed)")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_uvc_recognize_USBX_XX0_307(self, runtime=86400):
        self.video_long_test("USBX_XX0", bw=1, record_time=runtime)
        self.assertTrue(True, "usb host webcam test passed")

    @mark.id("BSP_USBX_XX0_308")
    @mark.desc("(USBX_XX0)的UVC Webcam中带宽24h帧率测试")
    @mark.args("runtime:default 24h in sec(1-86400 allowed)")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_uvc_recognize_USBX_XX0_308(self, runtime=86400):
        self.video_long_test("USBX_XX0", bw=2, record_time=runtime)
        self.assertTrue(True, "usb host webcam test passed")

    @mark.id("BSP_USBX_XX0_309")
    @mark.desc("(USBX_XX0)的UVC Webcam高带宽24h帧率测试")
    @mark.args("runtime:default 24h in sec(1-86400 allowed)")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_uvc_recognize_USBX_XX0_309(self, runtime=86400):
        self.video_long_test("USBX_XX0", bw=3, record_time=runtime)
        self.assertTrue(True, "usb host webcam test passed")

    @mark.id("BSP_USBX_120_310")
    @mark.desc("(USBX_XX0)的UVC Webcam dual cam")
    @mark.args("runtime:default 24h in sec(1-86400 allowed)")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_uvc_recognize_USBX_XX0_310(self, index=-1, runtime=86400):
        prefix = "USBX_XX0"
        node = self.uvc_find_node(prefix, dual=True)
        if node is None:
            self.fail(
                f"找不到uvc webacm，检查是否插入两个USB{self.get_speed(prefix)}.0规格的uvc webcam到{self.board_model.value}的{prefix}接口？!"
            )
        node1, node2 = node
        width, height = self.calc_width_height(prefix, 2)
        ffplay_cmd = (
            f"ffplay -f v4l2 -video_size {width}x{height} -framerate 30 /dev/{{}}"
        )
        self.logger.info(
            "Use Ffplay to run long run UVC test, Ctrl+C after 24H observation without error"
        )
        self.logger.info("使用 Ffplay 为你打开测试窗口，等待24H后观察画面是否有卡死。")
        self.logger.info(
            "注意，本测试必须伴随两个窗口分别执行  -a index=0 参数和 -a index=1 参数！！！"
        )
        if index == -1:
            hint = "本测试用例是半自动用例，需要长时间运行观察画面是否卡死，已检测到摄像头设备。请"
            hint += "打开两个终端窗口 分别执行 titan run case BSP_USBX_XX0_310 -a index=0 和 titan run case BSP_USBX_XX0_310 -a index=1\n"
            hint += "方便复制：\n"
            hint += "\ttitan run case BSP_USBX_XX0_310 -a index=0\n"
            hint += "\ttitan run case BSP_USBX_XX0_310 -a index=1\n"
            self.fail(hint)
        index = int(index)
        if index == 0:
            os.system(ffplay_cmd.format(node1))
        elif index == 1:
            os.system(ffplay_cmd.format(node2))
        else:
            self.fail(f"index {index} is invalid")
        self.assertNa(
            "半自动化测试用，需要人工记录测试结果(本打印在确认结果后Ctrl+C后才出现)"
        )

    ### RANGE TEMPLATE USB RANGE END####
    def cleanup_testcase(self):
        self.print_bw_report()
        self.cleanup_iter_cleanners()
        # these file use huge space
        self._execute(f"rm -f {uvc_resource_path}usb*_bw*_*.raw")
        # self._execute(f"rm -f {uvc_resource_path}usb*_bw*_*.mp4")
        self._execute(
            cmd_obj=f"umount {TEMP_MOUNT_DIR} ; rmdir {TEMP_MOUNT_DIR}", quiet=True
        )

    def cleanup_iteration(self):
        pass

    def after_testcase(self):
        self.device.release()
        if self.pc_device is not None:
            self.pc_device.release()
            self.pc_device = None


if __name__ == "__main__":

    def bold(s):
        return f"\033[1m{s}\033[0m"

    usage = """
"""
    import sys

    print(usage)
    # if len(sys.argv) > 1 and "help" in sys.argv[1]:
    #     print(f"exec `<KEY=val>.. titan run script {__file__}` to run tests")
    #     exit(0)
    # TestScript().execute(topo_config=topo_config)
