"""
Organization  : Spacemit
Author        : Pan Junzhong
Time          : 2025-4-21
Function      : bsp usb tester

Do not edit this file directly if current file is not the template file.
Generated from template file[1] via k2_host_gen.py
本文件为脚本生成，不要直接编辑本文件，除非本文件就是源文件。
[1]template file: bsptester/static_data/usb/templates/test_usb_host_net25g_usbX_XX0.py
"""

from bsptester.static_data.usb.lib.base import BspUsbTestBase
import os
from titanauto import mark, TestType
from titanauto.devices.topology import ChannelType
import sys

sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))


if os.getenv("TITAN_USB_DEVKIT", False):
    from bsptester.static_data.usb.lib.debug_config import *
else:
    from bsptester.static_data.usb.lib.config import *


usbnet25g_prefers = ("2.5G_LAN",)


class TestScript(BspUsbTestBase):
    """
    test usb host
    """

    def setup_testcase(self):
        hint = """####XXABBTUSB_PLACEHOLDER_SIPVER"""
        self.logger.info(hint)
        self.i_need_iter_cleanners()

    def before_testcase(self):
        # ssh 2 iface problem cannot be solved, we decide just use adb now...
        self.device = self.topo.get_device(channel=ChannelType.adb)
        self.pc_device = None
        self.install_packages_for_me()

    def setup_iteration(self):
        pass

    ### RANGE TEMPLATE USB RANGE BEGIN####
    @mark.id("BSP_USBX_XX0_420")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的2.5g网卡识别")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_net25g_recognize_USBX_XX0(self):
        """
        Test usb net.
        """
        self.logger.info("test_usb_net25g_recognize")
        net_name = self._find_net_name(
            "USBX_XX0", na_not_found=False, prefers=usbnet25g_prefers
        )
        output = self._single_line_cmd(f"ifconfig {net_name} up")
        self.assertNotIn(
            "No Such device",
            output,
            f"usb net interface {net_name} not found, "
            f"hardware change or malfunction driver",
        )
        output = self._single_line_cmd(f"ifconfig {net_name} down")

    @mark.id("BSP_USBX_XX0_421")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的2.5g网卡各向60s传输")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    @mark.pc_only
    def test_usb_net25g_transfer_USBX_XX0(self):
        """
        Test usb net.
        """
        self.logger.info("test_usb_net25g_transfer")
        self.i_need_pc_device()

        net_name = self._find_net_name(
            "USBX_XX0", na_not_found=False, prefers=usbnet25g_prefers
        )
        self._clean_net_if_fail(net_name)

        board_ip = self._config_net_test(net_name)
        self._iperf3_test(
            board_ip,
            IPERF3_RUNTIME_SEC,
            expected_Mbps=BW_THRES_X0_25G_IPERF3_RX_MBITPS,
            dir="tx",
            perf=False,
        )
        self._iperf3_test(
            board_ip,
            IPERF3_RUNTIME_SEC,
            expected_Mbps=BW_THRES_X0_25G_IPERF3_TX_MBITPS,
            dir="rx",
            perf=False,
        )
        self._iperf3_test(
            board_ip,
            IPERF3_RUNTIME_SEC,
            expected_Mbps=BW_THRES_X0_25G_IPERF3_BIDIR_MBITPS,
            dir="bidir",
            perf=False,
        )

        self._clean_net_cancel(net_name)
        self.assertTrue(True, "usb host net test passed")

    @mark.id("BSP_USBX_XX0_422")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的2.5g网卡bidir 360s带宽达标")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    @mark.pc_only
    def test_usb_net25g_bidir_perf_USBX_XX0(self):
        """
        Test usb net.
        """
        self.logger.info("test_usb_net25g_transfer")
        self.i_need_pc_device()

        net_name = self._find_net_name(
            "USBX_XX0", na_not_found=False, prefers=usbnet25g_prefers
        )
        self._clean_net_if_fail(net_name)

        board_ip = self._config_net_test(net_name)
        self._iperf3_test(
            board_ip,
            IPERF3_PERF_RUNTIME_SEC,
            expected_Mbps=BW_THRES_X0_25G_IPERF3_PERF_BIDIR_MBITPS,
            dir="bidir",
            perf=True,
        )

        self._clean_net_cancel(net_name)
        self.assertTrue(True, "usb host net test passed")

    @mark.id("BSP_USBX_XX0_423")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的2.5g网卡tx 360s带宽达标")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    @mark.pc_only
    def test_usb_net25g_tx_perf_USBX_XX0(self):
        """
        Test usb net.
        """
        self.logger.info("test_usb_net25g_transfer")
        self.i_need_pc_device()

        net_name = self._find_net_name(
            "USBX_XX0", na_not_found=False, prefers=usbnet25g_prefers
        )
        self._clean_net_if_fail(net_name)

        board_ip = self._config_net_test(net_name)
        self._iperf3_test(
            board_ip,
            IPERF3_PERF_RUNTIME_SEC,
            expected_Mbps=BW_THRES_X0_25G_IPERF3_PERF_TX_MBITPS,
            dir="tx",
            perf=True,
        )

        self._clean_net_cancel(net_name)
        self.assertTrue(True, "usb host net test passed")

    @mark.id("BSP_USBX_XX0_424")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的2.5g网卡rx 360s带宽达标")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    @mark.pc_only
    def test_usb_net25g_rx_perf_USBX_XX0(self):
        """
        Test usb net.
        """
        self.logger.info("test_usb_net25g_transfer")
        self.i_need_pc_device()

        net_name = self._find_net_name(
            "USBX_XX0", na_not_found=False, prefers=usbnet25g_prefers
        )
        self._clean_net_if_fail(net_name)

        board_ip = self._config_net_test(net_name)
        self._iperf3_test(
            board_ip,
            IPERF3_PERF_RUNTIME_SEC,
            expected_Mbps=BW_THRES_X0_25G_IPERF3_PERF_RX_MBITPS,
            dir="rx",
            perf=True,
        )

        self._clean_net_cancel(net_name)
        self.assertTrue(True, "usb host net test passed")

    @mark.id("BSP_USBX_XX0_425")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的2.5g网卡bidir 24h老化")
    @mark.args("runtime:default 24h in sec(1-86400 allowed)")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    @mark.pc_only
    def test_usb_net25g_bidir_longrun_USBX_XX0(self, runtime=IPERF3_LONGRUN_RUNTIME):
        """
        Test usb net.
        """
        self.logger.info("test_usb_net25g_transfer")
        self.i_need_pc_device()

        net_name = self._find_net_name(
            "USBX_XX0", na_not_found=False, prefers=usbnet25g_prefers
        )
        self._clean_net_if_fail(net_name)

        board_ip = self._config_net_test(net_name)
        self._iperf3_test(
            board_ip,
            runtime,
            expected_Mbps=BW_THRES_X0_25G_IPERF3_PERF_BIDIR_MBITPS,
            dir="bidir",
            perf=True,
            line_checking=True,
        )

        self._clean_net_cancel(net_name)
        self.assertTrue(True, "usb host net test passed")

    @mark.id("BSP_USBX_XX0_426")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的2.5g网卡tx 24h老化")
    @mark.args("runtime:default 24h in sec(1-86400 allowed)")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    @mark.pc_only
    def test_usb_net25g_tx_longrun_USBX_XX0(self, runtime=IPERF3_LONGRUN_RUNTIME):
        """
        Test usb net.
        """
        self.logger.info("test_usb_net25g_transfer")
        self.i_need_pc_device()

        net_name = self._find_net_name(
            "USBX_XX0", na_not_found=False, prefers=usbnet25g_prefers
        )
        self._clean_net_if_fail(net_name)

        board_ip = self._config_net_test(net_name)
        self._iperf3_test(
            board_ip,
            runtime,
            expected_Mbps=BW_THRES_X0_25G_IPERF3_PERF_TX_MBITPS,
            dir="tx",
            perf=True,
            line_checking=True,
        )

        self._clean_net_cancel(net_name)
        self.assertTrue(True, "usb host net test passed")

    @mark.id("BSP_USBX_XX0_427")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的2.5g网卡rx 24h老化")
    @mark.args("runtime:default 24h in sec(1-86400 allowed)")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    @mark.pc_only
    def test_usb_net25g_rx_longrun_USBX_XX0(self, runtime=IPERF3_LONGRUN_RUNTIME):
        """
        Test usb net.
        """
        self.logger.info("test_usb_net25g_transfer")
        self.i_need_pc_device()

        net_name = self._find_net_name(
            "USBX_XX0", na_not_found=False, prefers=usbnet25g_prefers
        )
        self._clean_net_if_fail(net_name)

        board_ip = self._config_net_test(net_name)
        self._iperf3_test(
            board_ip,
            runtime,
            expected_Mbps=BW_THRES_X0_25G_IPERF3_PERF_RX_MBITPS,
            dir="rx",
            perf=True,
            line_checking=True,
        )

        self._clean_net_cancel(net_name)
        self.assertTrue(True, "usb host net test passed")

    ### RANGE TEMPLATE USB RANGE END####
    def cleanup_testcase(self):
        self.print_bw_report()
        self.cleanup_iter_cleanners()
        self._execute(
            cmd_obj=f"umount {TEMP_MOUNT_DIR} ; rmdir {TEMP_MOUNT_DIR}", quiet=True
        )

    def cleanup_iteration(self):
        pass

    def after_testcase(self):
        self.device.release()
        if self.pc_device is not None:
            self.pc_device.release()
            self.pc_device = None


if __name__ == "__main__":

    def bold(s):
        return f"\033[1m{s}\033[0m"

    usage = """
"""
    import sys

    print(usage)
    # if len(sys.argv) > 1 and "help" in sys.argv[1]:
    #     print(f"exec `<KEY=val>.. titan run script {__file__}` to run tests")
    #     exit(0)
    # TestScript().execute(topo_config=topo_config)
