"""
Organization  : Spacemit
Author        : Pan Junzhong
Time          : 2025-4-21
Function      : bsp usb tester

Do not edit this file directly if current file is not the template file.
Generated from template file[1] via k2_host_gen.py
本文件为脚本生成，不要直接编辑本文件，除非本文件就是源文件。
[1]template file: bsptester/static_data/usb/templates/test_usb_host_awoken_usbX_XX0.py
"""


from bsptester.static_data.usb.lib.base import BspUsbTestBase
import time
import os
from titanauto import mark, TestType
from titanauto.devices.topology import ChannelType
import sys

sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))


if os.getenv("TITAN_USB_DEVKIT", False):
    from bsptester.static_data.usb.lib.debug_config import *
else:
    from bsptester.static_data.usb.lib.config import *


class TestScript(BspUsbTestBase):
    """
    test usb host
    """

    def setup_testcase(self):
        hint = """####XXABBTUSB_PLACEHOLDER_SIPVER"""
        self.logger.info(hint)
        self.i_need_iter_cleanners()

    def before_testcase(self):
        # ssh 2 iface problem cannot be solved, we decide just use adb now...
        self.device = self.topo.get_device(channel=ChannelType.adb)
        self.pc_device = None
        self.install_packages_for_me()

    def setup_iteration(self):
        pass

    ### RANGE TEMPLATE USB RANGE BEGIN####
    @mark.id("BSP_USBX_XX0_900")
    @mark.desc("usb休眠30s唤醒控制器正常")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_awoken_log_USBX_XX0(self):
        args = {"times": 30}
        # log is checked in the called case after resume
        self.logger.info("test_usb_awoken_log_USBX_XX0: going to run awoken case BSP_boot_awoken_0005")
        self.run_case_by_id("BSP_boot_awoken_0005", args=args)
        self.logger.info("test_usb_awoken_log_USBX_XX0: awoken case BSP_boot_awoken_0005 completed, waiting 5s before running next case")
        time.sleep(5)
        self.logger.info("test_usb_awoken_log_USBX_XX0: going to run usb roothub recognize case BSP_USBX_XX0_000")
        self.run_case_by_id("BSP_USBX_XX0_000")
        self.logger.info("test_usb_awoken_log_USBX_XX0: going to run usb disk recognize case BSP_USBX_XX0_100")
        self.run_case_by_id("BSP_USBX_XX0_100")
        # this assert is because titan script will check if function contain assert keywords
        self.assertTrue(True, "usb awoken test passed")

    @mark.id("BSP_USBX_XX0_901")
    @mark.desc("usb休眠5分钟唤醒综合测试")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_awoken_func_USBX_XX0(self):
        args = {"times": 5 * 60}
        # log is checked in the called case after resume
        self.run_case_by_id("BSP_boot_awoken_0005", args=args)
        time.sleep(5)
        self.logger.info("test_usb_awoken_log_USBX_XX0: going to run some usb function case")
        self.run_case_by_id("BSP_USBX_XX0_000")
        self.run_case_by_id("BSP_USBX_XX0_100")
        self.run_case_by_id("BSP_USBX_XX0_101")
        # this assert is because titan script will check if function contain assert keywords
        self.assertTrue(True, "usb awoken test passed")

    @mark.id("BSP_USBX_XX0_902")
    @mark.desc("usb休眠30分钟唤醒综合测试")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_awoken_func_long_USBX_XX0(self):
        args = {"times": 30 * 60}
        # log is checked in the called case after resume
        self.run_case_by_id("BSP_boot_awoken_0005", args=args)
        time.sleep(5)
        self.logger.info("test_usb_awoken_log_USBX_XX0: going to run some usb function case")
        self.run_case_by_id("BSP_USBX_XX0_000")
        self.run_case_by_id("BSP_USBX_XX0_100")
        self.run_case_by_id("BSP_USBX_XX0_101")

    @mark.id("BSP_USBX_XX0_903")
    @mark.desc("usb休眠5分钟唤醒共48小时老化")
    @mark.args("-")
    @mark.type(TestType.stability)
    @mark.ci(TestType.ci_daily)
    def test_usb_awoken_func_short_repeat_USBX_XX0(self):
        args = {"times": 5 * 60}
        total_time = 48 * 60 / 5
        for i in range(total_time):
            self.logger.info(f"===== USB awoken iteration {i+1}/{total_time} =====")
            # log is checked in the called case after resume
            # print log between each case
            self.logger.info("----- Going to run awoken case BSP_boot_awoken_0005 -----")
            self.run_case_by_id("BSP_boot_awoken_0005", args=args)
            time.sleep(5)
            self.run_case_by_id("BSP_USBX_XX0_000")
            self.logger.info("----- Going to run awoken case BSP_USBX_XX0_100 -----")
            self.run_case_by_id("BSP_USBX_XX0_100")
            self.logger.info("----- Going to run awoken case BSP_USBX_XX0_101 -----")
            self.run_case_by_id("BSP_USBX_XX0_101")

    @mark.id("BSP_USBX_XX0_904")
    @mark.desc("usb休眠30分钟唤醒共48小时老化")
    @mark.args("-")
    @mark.type(TestType.stability)
    @mark.ci(TestType.ci_daily)
    def test_usb_awoken_func_long_repeat_USBX_XX0(self):
        args = {"times": 30 * 60}
        total_time = 48 * 60 / 30
        for i in range(total_time):
            self.logger.info(f"===== USB awoken iteration {i+1}/{total_time} =====")
            # log is checked in the called case after resume
            # print log between each case
            self.logger.info("----- Going to run awoken case BSP_boot_awoken_0005 -----")
            self.run_case_by_id("BSP_boot_awoken_0005", args=args)
            time.sleep(5)
            self.run_case_by_id("BSP_USBX_XX0_000")
            self.logger.info("----- Going to run awoken case BSP_USBX_XX0_100 -----")
            self.run_case_by_id("BSP_USBX_XX0_100")
            self.logger.info("----- Going to run awoken case BSP_USBX_XX0_101 -----")
            self.run_case_by_id("BSP_USBX_XX0_101")

    ### RANGE TEMPLATE USB RANGE END####
    def cleanup_testcase(self):
        self.print_bw_report()
        self.cleanup_iter_cleanners()
        self._execute(
            cmd_obj=f"umount {TEMP_MOUNT_DIR} ; rmdir {TEMP_MOUNT_DIR}", quiet=True
        )

    def cleanup_iteration(self):
        pass

    def after_testcase(self):
        self.device.release()
        if self.pc_device is not None:
            self.pc_device.release()
            self.pc_device = None


if __name__ == "__main__":

    def bold(s):
        return f"\033[1m{s}\033[0m"

    usage = """
"""
    import sys

    print(usage)
    # if len(sys.argv) > 1 and "help" in sys.argv[1]:
    #     print(f"exec `<KEY=val>.. titan run script {__file__}` to run tests")
    #     exit(0)
    # TestScript().execute(topo_config=topo_config)
