"""
Organization  : Spacemit
Author        : Pan Junzhong
Time          : 2025-4-21
Function      : bsp usb tester

Do not edit this file directly if current file is not the template file.
Generated from template file[1] via k2_host_gen.py
本文件为脚本生成，不要直接编辑本文件，除非本文件就是源文件。
[1]template file: bsptester/static_data/usb/templates/test_usb_host_udisk_usbX_XX0.py
"""

from bsptester.static_data.usb.lib.base import BspUsbTestBase
import os
from titanauto import mark, TestType
from titanauto.devices.topology import ChannelType
import sys

sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))


if os.getenv("TITAN_USB_DEVKIT", False):
    from bsptester.static_data.usb.lib.debug_config import *
else:
    from bsptester.static_data.usb.lib.config import *


class TestScript(BspUsbTestBase):
    """
    test usb host
    """

    def setup_testcase(self):
        hint = """####XXABBTUSB_PLACEHOLDER_SIPVER"""
        self.logger.info(hint)
        self.i_need_iter_cleanners()

    def before_testcase(self):
        # ssh 2 iface problem cannot be solved, we decide just use adb now...
        self.device = self.topo.get_device(channel=ChannelType.adb)
        self.pc_device = None
        self.install_packages_for_me()

    def setup_iteration(self):
        pass

    ### RANGE TEMPLATE USB RANGE BEGIN####
    @mark.id("BSP_USBX_XX0_100")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的u盘识别")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_udisk_recognize_USBX_XX0(self):
        self.logger.info("BSP_USBX_XX0_100: 第0个USBX.0控制器上USBX.0速度的u盘识别")
        node = self.msc_find_node("USBX_XX0")
        if node is None:
            self.fail("找不到usb存储设备，检查是否插入要测试的规格的U盘到指定接口？!")
        self.assertTrue(True, "usb host msc test passed")

    @mark.id("BSP_USBX_XX0_101")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的u盘传输10g数据完整性")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_udisk_integrity_USBX_XX0(self):
        node = self.msc_find_node("USBX_XX0")
        if node is None:
            self.fail("找不到usb存储设备，检查是否插入要测试的规格的U盘到指定接口？!")
        size = FIO_X0_SEQRW_MSIZE
        timeout = FIO_X0_SEQRW_MSIZE / 5 + 20
        # prevent
        self._execute(f"umount {node}*", timeout=20)
        self._fio_test(
            self.device,
            node,
            "write",
            size,
            timeout,
            BW_THRES_X0_FIO_W_MBPS,
            is_timebased=False,
            is_perf=False,
            dontfail=False,
            fio_options="--verify=crc7",
        )
        self.assertTrue(True, "usb host msc test passed")

    @mark.id("BSP_USBX_XX0_102")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的u盘传输10g带宽达标")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_udisk_perf_USBX_XX0(self):
        node = self.msc_find_node("USBX_XX0")
        if node is None:
            self.fail("找不到usb存储设备，检查是否插入要测试的规格的U盘到指定接口？!")
        size = FIO_X0_SEQRW_MSIZE
        timeout = FIO_X0_SEQRW_MSIZE / 5 + 20

        # prevent
        self._execute(f"umount {node}*", timeout=20)
        temp1 = self._fio_test(
            self.device,
            node,
            "read",
            size,
            timeout,
            BW_THRES_X0_FIO_PERF_R_MBPS,
            is_timebased=False,
            is_perf=True,
            dontfail=True,
            fio_options="",
        )
        # prevent
        self._execute(f"umount {node}*", timeout=20)
        temp2 = self._fio_test(
            self.device,
            node,
            "write",
            size,
            timeout,
            BW_THRES_X0_FIO_PERF_W_MBPS,
            is_timebased=False,
            is_perf=True,
            dontfail=True,
            fio_options="",
        )
        self.assertTrue(
            temp1 and temp2, "第0个USBX.0控制器上USBX.0速度的u盘读写带宽不达标"
        )

    @mark.id("BSP_USBX_XX0_103")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的u盘文件系统挂载")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_udisk_mount_USBX_XX0(self):
        node = self.msc_find_node("USBX_XX0")
        if node is None:
            self.fail("找不到usb存储设备，检查是否插入要测试的规格的U盘到指定接口？!")
        mp = self.auto_mount_fs(
            node, ["ext4", "ext3", "ext2", "exfat", "vfat", "ntfs"], force_reformat=True
        )
        self.logger.info(f"mountpoint is on: {mp}")
        self.assertTrue(True, "usb host msc test passed")

    @mark.id("BSP_USBX_XX0_104")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的u盘文件系统数据完整性")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_udisk_mount_integrity_USBX_XX0(self):
        node = self.msc_find_node("USBX_XX0")
        if node is None:
            self.fail("找不到usb存储设备，检查是否插入要测试的规格的U盘到指定接口？!")
        mp = self.auto_mount_fs(
            node, ["ext4", "ext3", "ext2", "exfat", "vfat", "ntfs"], force_reformat=True
        )

        size = FIO_X0_SEQRW_MSIZE
        timeout = FIO_X0_SEQRW_MSIZE / 5 + 20
        fio_name = os.path.join(mp, FIO_FS_FILENAME)

        self._fio_test(
            self.device,
            fio_name,
            "write",
            size,
            timeout,
            BW_THRES_X0_FIO_W_MBPS,
            is_timebased=False,
            is_perf=False,
            dontfail=False,
            fio_options="--verify=crc7",
            post_verify_dev=node,
        )

    @mark.id("BSP_USBX_XX0_105")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的u盘50g随机读写老化")
    @mark.args("-")
    @mark.type(TestType.stability)
    @mark.ci(TestType.ci_daily)
    def test_usb_udisk_stress_randrw_USBX_XX0(self):
        dev_node = self.msc_find_node("USBX_XX0")
        if dev_node is None:
            self.fail("找不到usb存储设备，检查是否插入要测试的规格的U盘到指定接口？!")
        mp = self.auto_mount_fs(
            dev_node, ["ext4", "ext3", "ext2", "exfat"], force_reformat=False
        )
        if mp is None:
            self.logger.info("没找到U盘上的文件系统，在块设备层面进行直接测试")
            self._execute(f"umount {dev_node}*", timeout=20)
            fio_name = dev_node
        else:
            self.logger.info("找到U盘上的文件系统，在文件系统进行测试")
            fio_name = os.path.join(mp, FIO_FS_FILENAME)

        size = FIO_X0_RANDRW_LONGRUN_MSIZE
        timeout = FIO_X0_RANDRW_LONGRUN_RUNTIME_SEC

        self._fio_test(
            self.device,
            fio_name,
            "randrw",
            size,
            timeout,
            BW_THRES_X0_FIO_MIXED_MBPS,
            is_timebased=True,
            is_perf=False,
            dontfail=False,
            fio_options="",
            post_verify_dev=dev_node,
            bs_override=None,
        )
        # fio_options="--verify=crc7", post_verify_dev=node)

    @mark.id("BSP_USBX_XX0_106")
    @mark.desc("第0个USBX.0控制器上USBX.0速度的u盘50g顺序读写老化")
    @mark.args("-")
    @mark.type(TestType.stability)
    @mark.ci(TestType.ci_daily)
    def test_usb_udisk_stress_seqrw_USBX_XX0(self):
        dev_node = self.msc_find_node("USBX_XX0")
        if dev_node is None:
            self.fail("找不到usb存储设备，检查是否插入要测试的规格的U盘到指定接口？!")
        mp = self.auto_mount_fs(
            dev_node, ["ext4", "ext3", "ext2", "exfat"], force_reformat=False
        )
        if mp is None:
            self.logger.info("没找到U盘上的文件系统，在块设备层面进行直接测试")
            self._execute(f"umount {dev_node}*", timeout=20)
            fio_name = dev_node
        else:
            self.logger.info("找到U盘上的文件系统，在文件系统进行测试")
            fio_name = os.path.join(mp, FIO_FS_FILENAME)

        size = FIO_X0_RANDRW_LONGRUN_MSIZE
        timeout = FIO_X0_RANDRW_LONGRUN_RUNTIME_SEC

        self._fio_test(
            self.device,
            fio_name,
            "readwrite",
            size,
            timeout,
            BW_THRES_X0_FIO_MIXED_MBPS,
            is_timebased=True,
            is_perf=False,
            dontfail=False,
            fio_options="",
            post_verify_dev=dev_node,
            bs_override=None,
        )
        # fio_options="--verify=crc7", post_verify_dev=node)

    ### RANGE TEMPLATE USB RANGE END####
    def cleanup_testcase(self):
        self.print_bw_report()
        self.cleanup_iter_cleanners()
        self._execute(
            cmd_obj=f"umount {TEMP_MOUNT_DIR} ; rmdir {TEMP_MOUNT_DIR}", quiet=True
        )

    def cleanup_iteration(self):
        pass

    def after_testcase(self):
        self.device.release()
        if self.pc_device is not None:
            self.pc_device.release()
            self.pc_device = None


if __name__ == "__main__":

    def bold(s):
        return f"\033[1m{s}\033[0m"

    usage = """
"""
    import sys

    print(usage)
    # if len(sys.argv) > 1 and "help" in sys.argv[1]:
    #     print(f"exec `<KEY=val>.. titan run script {__file__}` to run tests")
    #     exit(0)
    # TestScript().execute(topo_config=topo_config)
