"""
Organization  : Spacemit
Author        : Pan Junzhong
Time          : 2024-08-07
Function      : bsp network tester

Do not edit this file directly if current file is not the template file.
Generated from template file[1] via k2_host_gen.py
本文件为脚本生成，不要直接编辑本文件，除非本文件就是源文件。
[1]template file: bsptester/static_data/usb/templates/test_usb_host_uart_usbX_XX0.py
"""

from titanaw.fileaw import FileAw
from bsptester.static_data.usb.lib.compatible_hell import (
    BianbuSDK,
    BoardModel,
)
from bsptester.static_data.usb.lib.base import BspUsbTestBase
import os
import re
import time
from titanauto import mark, TestType
from bsptester import static_data
import sys

sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))


topo_config = {
    "default": {
        # 通过uart连接到开发板
        "uart": {"port": "COM44", "baud": 115200, "line_flag": "# "},
        # 通过adb连接到开发板
        "adb": {"id": "fefefed696a6"},
    },
}


class TestScript(BspUsbTestBase):
    """
    test network, including ping, wget, iperf3
    """

    def before_testcase(self):
        self.device = self.topo.get_device()
        self.static_data_path = os.path.dirname(static_data.__file__)
        self.logger.info(f"path:{self.static_data_path}")
        self.uarttest_path = os.path.join(self.static_data_path, "usb", "uarttest")
        npath = os.path.join("/usr/bin/", "usbuarttest")
        # FileAw.download_to_board(self.uarttest_path, npath, self.device)
        self.device.run(f"cp {self.uarttest_path} {npath}")
        self.uarttest_path = npath
        self.logger.info(f"path:{self.uarttest_path}")
        cmd = f"chmod +x {self.uarttest_path}"
        self.logger.info(f"command:{cmd}")
        self.device.execute(cmd_obj=cmd, timeout=7)
        self.whereami = BianbuSDK.where_am_i(self)
        self.board_model = BoardModel.query_model(self)
        self.bw_result = []

    def setup_iteration(self):
        pass

    def find_uart_node(self, controller):
        n = self.usb_find_node_type("/dev/ttyUSB*", controller, "USB串口")
        if n is None:
            self.fail("找不到UART设备，请回滚日志看报错提示")
        return n

    ### RANGE TEMPLATE USB RANGE BEGIN####
    @mark.id("BSP_USBX_XX0_500")
    @mark.desc("测试USB HOST UART驱动基本功能，uart收发数据正常（包括特殊字符）")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_bsp_usb_uart500_USBX_XX0(self):
        """
        测试USB HOST UART驱动基本功能，uart收发数据正常（包括特殊字符）.

        Args:

        Returns:
        """
        uart_node = self.find_uart_node("USBX_XX0")
        cmd = f"{self.uarttest_path} {uart_node} 100 1 115200"
        self.logger.info(f"command:{cmd}")
        code, output, error = self.device.execute(cmd_obj=cmd, timeout=7)
        self.logger.info(output)
        if "check your uart path" in output:
            self.fail(
                "No USB Uart Attached ? Contact to check any uart connect to usb?"
            )
        self.assertEqual(code, 0, f"error: f{error}")
        self.assertIn("error_times = 0", output, f"{cmd} error: f{error}")

    @mark.id("BSP_USBX_XX0_501")
    @mark.desc("测试USB HOST UART驱动基本功能，设置收发波特率")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_bsp_usb_uart501_USBX_XX0(self):
        """
        测试USB HOST UART驱动基本功能，设置收发波特率

        Args:

        Returns:
        """
        uart_node = self.find_uart_node("USBX_XX0")
        baus = [9600, 19200, 38400, 115200, 230400, 921600, 1500000, 2000000, 3000000]
        for i in baus:
            cmd = f"{self.uarttest_path} {uart_node} 100 1 {i}\n"
            self.logger.info(f"command:{cmd}")
            code, output, error = self.device.execute(cmd_obj=cmd, timeout=10)
            if "check your uart path" in output:
                self.assertNa(
                    "No USB Uart Attached ? Contact junzhong to check any uart connect to usb?"
                )
            match = re.search(r"iospeed = (\d+)\(input\),(\d+)\(output\)", output)
            print(match)
            input_speed = int(match.group(1))
            output_speed = int(match.group(2))
            self.assertEqual(code, 0, f"error: f{error}")
            self.logger.info(output)
            self.assertIn("error_times = 0", output, f"command {cmd} error: f{error}")
            self.assertEqual(
                input_speed,
                output_speed,
                f"input speed和output speed不相等. error: \n f{error}",
            )
            # K3 CPU is super fast, in case serial device is not released
            time.sleep(0.5)

    @mark.id("BSP_USBX_XX0_502")
    @mark.desc("测试USB HOST UART数据稳定性")
    @mark.args("baud:波特率default:115200")
    @mark.type(TestType.stability)
    @mark.ci(TestType.ci_daily)
    def test_bsp_usb_uart502_USBX_XX0(self, baud=115200):
        """
        测试USB HOST UART传输大数据量

        Args:

        Returns:
        """
        # uarttest args: data_size(in bytes), test_times, baudrate
        uart_node = self.find_uart_node("USBX_XX0")
        # help me loop until reach 24h:
        start_time = time.time()
        duration = 86400  # 24 hours in seconds
        while (time.time() - start_time) < duration:
            cmd = f"{self.uarttest_path} {uart_node} 100 1000 {baud}"
            self.logger.info(f"command:{cmd}")
            code, output, error = self.device.execute(cmd_obj=cmd, timeout=120)
            self.logger.info(output)
            if "check your uart path" in output:
                self.assertNa(
                    "No USB Uart Attached ? Contact junzhong to check any uart connect to usb?"
                )
            self.assertEqual(code, 0, f"error: f{error}")
        self.assertIn("error_times = 0", output, f"command {cmd} error: f{error}")

    ### RANGE TEMPLATE USB RANGE END####
    def cleanup_iteration(self):
        pass

    def after_testcase(self):
        self.device.release()


if __name__ == "__main__":

    def bold(s):
        return f"\033[1m{s}\033[0m"

    usage = """
"""
    import sys

    print(usage)
    # if len(sys.argv) > 1 and "help" in sys.argv[1]:
    #     print(f"exec `<KEY=val>.. titan run script {__file__}` to run tests")
    #     exit(0)
    # TestScript().execute(topo_config=topo_config)
