"""
Organization  : Spacemit
Author        : Pan Junzhong
Time          : 2025-4-21
Function      : bsp usb tester

Do not edit this file directly if current file is not the template file.
Generated from template file[1] via k2_host_gen.py
本文件为脚本生成，不要直接编辑本文件，除非本文件就是源文件。
[1]template file: bsptester/static_data/usb/templates/test_usb_host_hub_usbX_XX0.py
"""

from bsptester.static_data.usb.lib.compatible_hell import (
    BoardModel,
)
from bsptester.static_data.usb.lib.base import BspUsbTestBase
import os
from titanauto import mark, TestType
from titanauto.devices.topology import ChannelType
import sys

sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))


if os.getenv("TITAN_USB_DEVKIT", False):
    from bsptester.static_data.usb.lib.debug_config import *
else:
    from bsptester.static_data.usb.lib.config import *


class TestScript(BspUsbTestBase):
    """
    test usb host
    """

    def setup_testcase(self):
        hint = """####XXABBTUSB_PLACEHOLDER_SIPVER"""
        self.logger.info(hint)
        self.i_need_iter_cleanners()

    def before_testcase(self):
        # ssh 2 iface problem cannot be solved (two iface on a same subnet cannot ping/ssh/iperf),
        # we decide just use adb now... But We cannot run adb on USB0... Never mind, since
        # we always need USB0 to flash image, we may NEVER deploy this into actual automatic test
        # environment. This is stupid.
        prefix = "USBX_XX0"
        if prefix.startswith("USB3_0"):
            what_channel_to_use = ChannelType.ssh
        else:
            what_channel_to_use = ChannelType.adb
        self.device = self.topo.get_device(channel=what_channel_to_use)
        self.pc_device = None
        self.install_packages_for_me()

    def setup_iteration(self):
        pass

    ### RANGE TEMPLATE USB RANGE BEGIN####
    @mark.id("BSP_USBX_XX0_000")
    @mark.desc("usb roothub的lsusb检测(USBX_XX0)")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_root_hub_recognize_USBX_XX0(self):
        bus_number = self.get_bus_number("USBX_XX0")
        busnum = bus_number.replace("usb", "")
        # if busnum = 1, we have to format  to 01, this should use
        # print format to gen, prepend 0 to single digit number
        root_hub_cnt = self._single_line_cmd("lsusb | grep '{} Device' | grep 'root hub' | wc -l".format(busnum.zfill(2)))
        collect = self._single_line_cmd("lsusb")
        collect += self._single_line_cmd("lsusb -tv")
        root_hub_cnt = int(root_hub_cnt)
        self.assertGreaterEqual(
            root_hub_cnt,
            1,
            f"only {root_hub_cnt} usb root hub detected , controller may not up! FYI: {collect}",
        )

    @mark.id("BSP_USBX_XX0_001")
    @mark.desc("usb hub(板载)的lsusb检测(USBX_XX0)")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_onboard_hub_recognize_USBX_XX0(self):
        self.dont_na_boards([BoardModel.DEB1, BoardModel.MPIPRO, BoardModel.JUPITER, BoardModel.K2DEB, BoardModel.K2COM26])
        # normally, one board have only one onboard hub
        speed_num = self.get_speed("USBX_XX0")
        fyi = self._single_line_cmd("lsusb")
        root_hub_cnt = self._single_line_cmd(
            f"lsusb | grep -E '1d6b:000{speed_num}' | wc -l"
        )
        root_hub_cnt = int(root_hub_cnt)
        self.assertGreaterEqual(
            root_hub_cnt,
            1,
            f"only {root_hub_cnt} usb root hub detected , controller may not up!",
        )
        # search for VL817 and GL850
        prefix_817 = '0' if speed_num == '3' else '2'
        hub_usb_cnt = self._single_line_cmd(
            f"lsusb | grep -E '(2109:{prefix_817}817)|(05e3:0608)|(1a40:0101)' | wc -l"
        )

        hub_usb_cnt = int(hub_usb_cnt)
        self.assertGreaterEqual(
            hub_usb_cnt,
            1,
            f"only {hub_usb_cnt} usb onboard hub detected, hub may not up! FYI: {fyi}",
        )
        self.assertTrue(True, "usb host spacemit onboard hub test passed")

    @mark.id("BSP_USBX_XX0_002")
    @mark.desc("usb hub(外接)上接U盘网卡交替测试(USBX_XX0)")
    @mark.args("-")
    @mark.type(TestType.function)
    @mark.ci(TestType.ci_daily)
    def test_usb_hub_multi_function_USBX_XX0(self):
        self.i_need_pc_device()
        node = self.msc_find_node("USBX_XX0")
        net_name = self._find_net_name("USBX_XX0", na_not_found=False)
        self._clean_net_if_fail(net_name)
        board_ip = self._config_net_test(net_name)

        mp = self.auto_mount_fs(
            node, ["ext4", "ext3", "ext2", "exfat"], force_reformat=False
        )
        if mp is None:
            self.logger.info("没找到U盘上的文件系统，在块设备层面进行直接测试")
            self._execute(f"umount {node}*", timeout=20)
            fio_name = node
        else:
            self.logger.info("找到U盘上的文件系统，在文件系统进行测试")
            fio_name = os.path.join(mp, FIO_FS_FILENAME)

        if node is None:
            self.fail("找不到usb存储设备，检查是否插入要测试的规格的U盘到指定接口？!")
        size = FIO_X0_SEQRW_MSIZE
        timeout = FIO_X0_SEQRW_MSIZE / 5 + 20

        self._iperf3_test(
            board_ip,
            IPERF3_RUNTIME_SEC,
            expected_Mbps=BW_THRES_X0_IPERF3_BIDIR_MBITPS,
            dir="bidir",
            perf=False,
        )

        self._fio_test(
            self.device,
            fio_name,
            "write",
            size,
            timeout,
            BW_THRES_X0_FIO_W_MBPS,
            is_timebased=False,
            is_perf=False,
            dontfail=False,
            fio_options="--verify=crc7",
            post_verify_dev=node,
        )

        self._iperf3_test(
            board_ip,
            IPERF3_RUNTIME_SEC,
            expected_Mbps=BW_THRES_X0_IPERF3_BIDIR_MBITPS,
            dir="bidir",
            perf=False,
        )

        self._fio_test(
            self.device,
            fio_name,
            "write",
            size,
            timeout,
            BW_THRES_X0_FIO_W_MBPS,
            is_timebased=False,
            is_perf=False,
            dontfail=False,
            fio_options="--verify=crc7",
            post_verify_dev=node,
        )

        self._clean_net_cancel(net_name)

    ### RANGE TEMPLATE USB RANGE END####
    def cleanup_testcase(self):
        self.print_bw_report()
        self.cleanup_iter_cleanners()
        self._execute(
            cmd_obj=f"umount {TEMP_MOUNT_DIR} ; rmdir {TEMP_MOUNT_DIR}", quiet=True
        )

    def cleanup_iteration(self):
        pass

    def after_testcase(self):
        self.device.release()
        if self.pc_device is not None:
            self.pc_device.release()
            self.pc_device = None


if __name__ == "__main__":

    def bold(s):
        return f"\033[1m{s}\033[0m"

    usage = """
"""
    import sys

    print(usage)
    # if len(sys.argv) > 1 and "help" in sys.argv[1]:
    #     print(f"exec `<KEY=val>.. titan run script {__file__}` to run tests")
    #     exit(0)
    # TestScript().execute(topo_config=topo_config)
